# Generated by Django 5.0.3 on 2024-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('mrp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_stock', models.IntegerField()),
                ('sold_stock', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
